# Generated by Django 3.1.7 on 2021-11-21 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0003_auto_20211120_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='emails_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
