# Generated by Django 3.1.7 on 2021-11-30 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0006_auto_20211121_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=64)),
                ('item_description', models.TextField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image_url', models.URLField(blank=True)),
                ('cart_list', models.ManyToManyField(blank=True, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('item_buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bought', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='knivesharpener.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
