# Generated by Django 3.1.7 on 2021-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0008_listing_animation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='animation_id',
            new_name='animation_header',
        ),
        migrations.AddField(
            model_name='listing',
            name='animation_image',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
