# Generated by Django 3.1.7 on 2021-11-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0010_auto_20211130_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
