# Generated by Django 3.1.7 on 2021-12-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0011_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='adress',
            new_name='address',
        ),
    ]
