# Generated by Django 3.1.7 on 2021-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0012_auto_20211204_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
