# Generated by Django 3.1.7 on 2021-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0013_cart_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
