# Generated by Django 3.1.7 on 2021-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knivesharpener', '0014_cart_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
